# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4.1
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/home/jxj/Xilinx/Vivado/2017.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z045ffg900-2 ../xilinx_com_hls_mixer_duc_1_0.zip
