connect_bd_intf_net -boundary_type upper [get_bd_intf_pins openwifi_ip/M00_AXI] [get_bd_intf_pins sys_ps7/S_AXI_ACP]
connect_bd_intf_net -boundary_type upper [get_bd_intf_pins openwifi_ip/M00_AXI1] [get_bd_intf_pins sys_ps7/S_AXI_HP3]
connect_bd_net [get_bd_pins openwifi_ip/fifo_rd_en] [get_bd_pins axi_ad9361_dac_dma/fifo_rd_en]
connect_bd_net [get_bd_pins axi_ad9361_dac_dma/fifo_rd_dout] [get_bd_pins openwifi_ip/fifo_rd_dout]
connect_bd_net [get_bd_pins openwifi_ip/fifo_rd_underflow] [get_bd_pins axi_ad9361_dac_dma/fifo_rd_underflow]
connect_bd_net [get_bd_pins openwifi_ip/dac_data] [get_bd_pins util_ad9361_dac_upack/dac_data]
connect_bd_net [get_bd_pins util_ad9361_dac_upack/dac_valid] [get_bd_pins openwifi_ip/dac_valid]
connect_bd_net [get_bd_pins openwifi_ip/dac_dunf] [get_bd_pins axi_ad9361_dac_fifo/din_unf]
connect_bd_intf_net -boundary_type upper [get_bd_intf_pins openwifi_ip/S00_AXI] [get_bd_intf_pins sys_ps7/M_AXI_GP1]
connect_bd_net [get_bd_pins openwifi_ip/adc_clk] [get_bd_pins util_ad9361_divclk/clk_out]
connect_bd_net [get_bd_pins openwifi_ip/adc_rst] [get_bd_pins util_ad9361_divclk_reset/peripheral_reset]
connect_bd_net [get_bd_pins openwifi_ip/adc_data] [get_bd_pins util_ad9361_adc_pack/adc_data]
connect_bd_net [get_bd_pins openwifi_ip/adc_valid] [get_bd_pins util_ad9361_adc_pack/adc_valid]
connect_bd_net [get_bd_pins openwifi_ip/ext_reset_in] [get_bd_pins sys_ps7/FCLK_RESET2_N]
startgroup
create_bd_port -dir I -from 7 -to 0 gpio_status_1
connect_bd_net [get_bd_pins /openwifi_ip/gpio_status] [get_bd_ports gpio_status_1]
endgroup
connect_bd_net [get_bd_pins openwifi_ip/m_axi_mm2s_aclk] [get_bd_pins sys_ps7/FCLK_CLK2]
connect_bd_net [get_bd_pins sys_ps7/S_AXI_HP3_ACLK] [get_bd_pins sys_ps7/FCLK_CLK2]
connect_bd_net [get_bd_pins sys_ps7/S_AXI_ACP_ACLK] [get_bd_pins sys_ps7/FCLK_CLK2]
connect_bd_net [get_bd_pins sys_ps7/M_AXI_GP1_ACLK] [get_bd_pins sys_ps7/FCLK_CLK2]
delete_bd_objs [get_bd_nets ps_intr_04_1]
connect_bd_net [get_bd_pins sys_concat_intc/In4] [get_bd_pins openwifi_ip/tx_itrpt0]
delete_bd_objs [get_bd_nets ps_intr_05_1]
connect_bd_net [get_bd_pins sys_concat_intc/In5] [get_bd_pins openwifi_ip/tx_itrpt1]
delete_bd_objs [get_bd_nets ps_intr_06_1]
connect_bd_net [get_bd_pins sys_concat_intc/In6] [get_bd_pins openwifi_ip/mm2s_introut]
delete_bd_objs [get_bd_nets ps_intr_02_1]
connect_bd_net [get_bd_pins sys_concat_intc/In2] [get_bd_pins openwifi_ip/mm2s_introut1]
delete_bd_objs [get_bd_nets ps_intr_01_1]
connect_bd_net [get_bd_pins sys_concat_intc/In1] [get_bd_pins openwifi_ip/rx_pkt_intr]
delete_bd_objs [get_bd_nets ps_intr_03_1]
connect_bd_net [get_bd_pins sys_concat_intc/In3] [get_bd_pins openwifi_ip/s2mm_introut]
delete_bd_objs [get_bd_nets ps_intr_07_1]
connect_bd_net [get_bd_pins sys_concat_intc/In7] [get_bd_pins openwifi_ip/s2mm_introut1]
save_bd_design

