# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.4.1
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/home/jxj/Xilinx/Vivado/2017.4/bin/vivado  -notrace -mode batch -source run_ippack.tcl
